{
    "tests.test_crypto.TestPKey.test_pregeneration": ["src.OpenSSL.crypto.PKey.type", "src.OpenSSL.crypto.PKey.bits", "src.OpenSSL.crypto.PKey.check"],
    "tests.test_ssl.TestConnection.test_get_peer_cert_chain_none": ["src.OpenSSL.SSL.Connection.get_peer_cert_chain"],
    "tests.test_ssl.TestMemoryBIO.test_socket_overrides_memory": ["src.OpenSSL.SSL.Connection.bio_read","src.OpenSSL.SSL.Connection.bio_write"],
    "tests.test_ssl.TestServerNameCallback.test_no_servername": ["src.OpenSSL.SSL.Context.set_tlsext_servername_callback", "src.OpenSSL.SSL.Connection.get_servername"],
    "tests.test_ssl.TestConnection.test_get_cipher_version": ["src.OpenSSL.SSL.Connection.get_cipher_version"],
    "tests.test_crypto.TestFunction.test_load_privatekey_passphrase_wrong_return_type": ["src.OpenSSL.crypto.load_privatekey"],
    "tests.test_crypto.TestPKey.test_check_pr_897": ["src.OpenSSL.crypto.load_privatekey", "src.OpenSSL.crypto.PKey.check"],
    "tests.test_ssl.TestDTLS.test_timeout": ["src.OpenSSL.SSL.Connection.DTLSv1_get_timeout", "src.OpenSSL.SSL.Connection.DTLSv1_handle_timeout"],
    "tests.test_crypto.TestX509Req.test_construction": ["src.OpenSSL.crypto.X509Req.__init__"],
    "tests.test_crypto.TestRevoked.test_set_reason_invalid_reason": ["src.OpenSSL.crypto.Revoked.set_reason"],
    "tests.test_crypto.TestRevoked.test_reason": ["src.OpenSSL.crypto.Revoked.all_reasons", "src.OpenSSL.crypto.Revoked.set_reason", "src.OpenSSL.crypto.Revoked.get_reason"],
    "tests.test_ssl.TestConnection.test_set_context": ["src.OpenSSL.SSL.Connection.set_context"],
    "tests.test_crypto.TestX509Name.test_only_string_attributes": ["src.OpenSSL.crypto.X509.get_subject"],
    "tests.test_crypto.TestCRL.test_dump_crl": ["src.OpenSSL.crypto.dump_crl"],
    "tests.test_crypto.TestX509Req.test_undef_oid": ["src.OpenSSL.crypto.X509Extension.get_short_name"],
    "tests.test_crypto.TestFunction.test_load_privatekey_wrongPassphrase": ["src.OpenSSL.crypto.load_privatekey"],
    "tests.test_ssl.TestContext.test_set_timeout_wrong_args": ["src.OpenSSL.SSL.Context.set_timeout"],
    "tests.test_ssl.TestContextConnection.test_use_certificate": ["src.OpenSSL.SSL.Context.use_certificate", "src.OpenSSL.SSL.Connection.use_certificate"],
    "tests.test_ssl.TestConnection.test_connect_wrong_args": ["src.OpenSSL.SSL.Connection.connect"],
    "tests.test_crypto.TestX509StoreContext.test_get_verified_chain_invalid_chain_no_root": ["src.OpenSSL.crypto.X509StoreContext.get_verified_chain"],
    "tests.test_crypto.TestX509StoreContext.test_verify_with_ca_file_location": ["src.OpenSSL.crypto.X509Store.load_locations", "src.OpenSSL.crypto.X509StoreContext.verify_certificate"],
    "tests.test_ssl.TestContext.test_set_default_verify_paths": ["src.OpenSSL.SSL.Context.set_default_verify_paths", "src.OpenSSL.SSL.Connection.send"],
    "tests.test_ssl.TestContext.test_set_options": ["src.OpenSSL.SSL.Context.set_options"],
    "tests.test_ssl.TestConnection.test_set_verify_overrides_context": ["src.OpenSSL.SSL.Context.set_verify"],
    "tests.test_crypto.TestX509.test_convert_from_cryptography": ["src.OpenSSL.crypto.X509Req.from_cryptography"],
    "tests.test_crypto.TestSignVerify.test_sign_with_large_key": ["src.OpenSSL.crypto.sign"],
    "tests.test_crypto.TestX509.test_version": ["src.OpenSSL.crypto.X509.set_version", "src.OpenSSL.crypto.X509.get_version"],
    "tests.test_ssl.TestContext.test_set_keylog_callback": ["src.OpenSSL.SSL.Context.set_keylog_callback"],
    "tests.test_ssl.TestContext.test_set_verify_callback_exception": ["src.OpenSSL.SSL.Context.set_verify"],
    "tests.test_ssl.TestContext.test_set_session_id_unicode": ["src.OpenSSL.SSL.Context.set_session_id"],
    "tests.test_crypto.TestX509Store.test_load_locations_fails_when_all_args_are_none": ["src.OpenSSL.crypto.X509Store.load_locations"],
    "tests.test_crypto.TestX509Req.test_convert_from_cryptography_unsupported_type": ["src.OpenSSL.crypto.X509Req.from_cryptography"],
    "tests.test_crypto.TestX509.test_invalid_digest_algorithm": ["src.OpenSSL.crypto.X509.digest"],
    "tests.test_util.TestErrors.test_exception_from_error_queue_nonexistent_reason": ["src.OpenSSL._util.exception_from_error_queue"],
    "tests.test_crypto.TestX509.test_convert_to_cryptography_key": ["src.OpenSSL.crypto.X509.to_cryptography"],
    "tests.test_crypto.TestCRL.test_export_md5_digest": ["src.OpenSSL.crypto.CRL.export"],
    "tests.test_ssl.TestContext.test_fallback_path_is_not_file_or_dir": ["src.OpenSSL.SSL.Context._fallback_default_verify_paths"],
    "tests.test_ssl.TestContext.test_set_verify_wrong_callable_arg": ["src.OpenSSL.SSL.Context.set_verify"],
    "tests.test_crypto.TestX509.test_set_notBefore": ["src.OpenSSL.crypto.X509.set_notBefore"]
}